### ISSUE TITLE
New category for Consumer Electronics related APIs

### ISSUE THREAD

**Issue by realtechspecs** [public-apis/public-apis#2913] opened 2021-11-21 23:12 UTC

**Comment by pawelborkar** [comment] 2021-11-23 08:25
Thanks for opening this issue and for the suggestion as well @realtechspecs  for the Consumer Electronics Category. But as the contributing guide suggests we need atleast 3 entries in order to make a new category.

So, in order to make a new category please make sure you have at least 3 public apis or APIs with a generous free trial in order to add them into this newly created category.

If in some case you don't wanna invest your time finding the other 2 APIs then it's totally fine. We'll keep this issue open until some other APIs falling under the Consumer Electronics is introduced by other community members and then we'll include this one into the Consumer Electronics category as well.

**Comment by Branscott1780** [comment] 2021-11-30 14:10
A good category would be name and global user name to insure a uid is made

**Comment by mgncodes** [comment] 2021-12-11 12:46
Hi @pawelborkar , I'm interested to contribute to this issue. Could you please assign this to me?

**Comment by pawelborkar** [comment] 2021-12-12 08:03
Hey @mgncodes,

Thanks for showing your interest in it. 
As you know this issue is more of a new category request and not a bug fix which means we don't need to assign it to anyone. Make a PR with the context stated [here](https://github.com/public-apis/public-apis/issues/2913#issuecomment-976253632) and reading the contributing guide and we'll be happy to review it.

**Comment by Umer19** [comment] 2021-12-16 16:18
https://github.com/public-apis/public-apis/issues/2913#issue-1059514704

**Comment by codewithpom** [comment] 2021-12-19 13:00
How is this api https://developer.samsung.com/smarttv/develop/api-references/samsung-product-api-references.html

**Comment by codewithpom** [comment] 2021-12-19 13:05
And even how is this one https://dev.mi.com/docs/passport/en/open-api/

**Comment by shashankskb18700** [comment] 2022-01-01 17:25
please review this api  https://octopart.com/api

**Comment by codewithpom** [comment] 2022-01-02 03:09
Thanks

**Comment by codewithpom** [comment] 2022-01-02 03:12
@shashankskb18700 sorry but the API above is not free you need a credit card for that and we only keep free APIs

**Comment by shashankskb18700** [comment] 2022-01-02 11:47
okay

**Comment by shashankskb18700** [comment] 2022-01-02 12:01
please check this out 

https://fonoapi.freshpixl.com/

https://github.com/shakee93/fonoapi

**Comment by CodeSofty** [comment] 2022-01-14 01:26
Can we use our own APIs, if we've built one?

**Comment by array-in-a-matrix** [comment] 2022-01-19 23:19
> please check this out
> 
> https://fonoapi.freshpixl.com/
> 
> https://github.com/shakee93/fonoapi


This API seems abandoned. The readme says the API is down and the repo hasn't been updated since 2020.

**Comment by Slizzywhippy1** [comment] 2022-01-20 00:45
Hello

**Comment by Code-Arpan** [comment] 2022-03-02 17:46
I'm a beginner please tell me what I have to do in this issue.

**Comment by pawelborkar** [comment] 2022-03-03 06:22
> I'm a beginner please tell me what I have to do in this issue.

Hi Arpan,
Welcome to public-apis. This issue is more of an announcement for creating a new category in the project rather than an issue itself. As you can read in the [Contributing Guide](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md) creating a new category requires at least 3 working APIs related to that specific category which a contributor wants to create and should follow other criteria mentioned in the contributing guide.

**Comment by Code-Arpan** [comment] 2022-03-03 07:38
Hey, @pawelborkar 

Please check this out -

| [FITBIT ](https://dev.fitbit.com) | Fitbit user data, collected by their products | OAuth | Yes | Unknown |

**Closed** 2022-10-14 08:14 UTC
Labels: good first issue, enhancement, new category
