### ISSUE TITLE
Chuck Norris Database Error 404

### ISSUE THREAD

**Issue by cRoCx** [public-apis/public-apis#3346] opened 2022-11-13 00:10 UTC
The "Chuck Norris Database" (http://www.icndb.com/api/) inside the "Games & Comics" section shows a 404. The domain "icndb.com" itself also shows a 404.
> Not Found
> The requested URL was not found on this server.
> Apache/2.4.52 (Ubuntu) Server at www.icndb.com Port 80

**Comment by darless** [comment] 2023-01-09 19:26
Duplicate of: #3399 - PR with removal in #3409

**Comment by matheusfelipeog** [comment] 2023-08-14 00:29
Hi @cRoCx 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104

**Closed by matheusfelipeog** 2023-08-14 00:29 UTC
Labels: enhancement
