### ISSUE TITLE
Hacktoberfest 2021

### ISSUE THREAD

**Issue by matheusfelipeog** [public-apis/public-apis#2107] opened 2021-10-02 14:10 UTC
<div align="center">
    <img src="https://user-images.githubusercontent.com/50463866/135718788-5e4b1937-6593-47db-b6d8-789d89f39097.png" width="400px" />
</div>
<p align="center"><strong>Open source is changing the world – one contribution at a time.</strong></p>

<p align="center"><strong>Support open source throughout October!</strong></p>

<p align="center">Hacktoberfest encourages participation in the open source community, which grows bigger every year. Complete the 2021 challenge and earn a limited edition T-shirt.</p>

---

## Hacktoberfest and Public APIs

Public APIs is participating in hacktoberfest 2021 and needs your help to improve it even more. Please feel free to open questions / request requests and we will be happy to review your contribution. :octocat: 

## Important

Before making any contribution, please read our [contribution guide](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md) to help you out. In it you will find all the requirements for an API to be listed here.

After you make your contribution, a sequence of automated tests will be run to expedite a review by one of the maintainers (@matheusfelipeog, @pawelborkar, @marekdano and @yannbertrand).

Please stay tuned for test results. They will inform you as quickly as possible if your contribution has any problems. If the tests fail, your contribution has a problem and must be fixed in order to be merged.

**Example of test failure:**

![image](https://user-images.githubusercontent.com/50463866/135719841-d52fc5e0-610e-4255-a2ce-5d370b1987c2.png)

See more information about the failure by clicking on the `Details` link

**Example of test success:**

![image](https://user-images.githubusercontent.com/50463866/135719851-8dd89cd1-cea4-47a9-a922-56ecace486c7.png)

---

Learn more about Hacktoberfest 2021 at: https://hacktoberfest.digitalocean.com/

**Comment by cyberbuddy-manas** [comment] 2021-10-02 17:46
Great, am interested to contribute to this repository. Hope it all works out well.

**Comment by saraswathy-krish** [comment] 2021-10-02 20:08
Hi @matheusfelipeog , I am interested to contribute to this repository and would love to take up on an issue.

**Comment by matheusfelipeog** [comment] 2021-10-02 21:03
Very good @cyberbuddy-manas and @saraswathy-krish, we look forward to your contribution ;)

**Comment by priyanshu688** [comment] 2021-10-03 03:31
I would like to contribute to this..Can I work on this? @matheusfelipeog

**Comment by susheelg1197** [comment] 2021-10-03 03:39
I am very interested to contribute.

**Comment by matheusfelipeog** [comment] 2021-10-03 03:42
> I would like to contribute to this..Can I work on this? @matheusfelipeog

Of course @priyanshu688, any contribution is welcome.

**Comment by priyanshm07** [comment] 2021-10-03 04:23
Hey, @matheusfelipeog 
I would like to add some APIs to the repo as my contribution.

**Comment by priyanshu688** [comment] 2021-10-03 04:42
@matheusfelipeog thank you...what exactly here I need to do...can you tell me?

**Comment by KadariSadhvika903** [comment] 2021-10-03 05:06
Hi, @matheusfelipeog. I am interested to contribute to this repository.

**Comment by Beyonday008** [comment] 2021-10-03 05:51
I am interested to contribute..

**Comment by pawelborkar** [comment] 2021-10-03 06:10
Hey guys thank you so much for showing your interest in the project, make sure to read the [Contributing Guide](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md) completely before opening a PR, we follow one commit one API policy at public APIs, so make sure you abide by this in order to make the reviewing process faster. 

Thanks 😊

**Comment by pawelborkar** [comment] 2021-10-03 06:11
Read More at #1700

**Comment by swaraj-ssk** [comment] 2021-10-03 06:56
Can I contribute to this? I am very interested to do so.

**Comment by Alankruthisaieni** [comment] 2021-10-03 07:00
Sir Please look into my PR Add Geek-Jokes API #2168

**Comment by pawelborkar** [comment] 2021-10-03 07:01
Sure, We are open to all the contribution please make sure to read the Contributing Guide before your open a PR

**Comment by pawelborkar** [comment] 2021-10-03 07:02
> Sir Please look into my PR Add Geek-Jokes API #2168

Please have patience we'll be reviewing the PRs on the first come first serve basis.

Thanks

**Comment by mgeorgiou** [comment] 2021-10-03 09:50
Starred! This will be my go-to repo for finding public APIs from now on. Cheers

**Comment by Ritika457** [comment] 2021-10-03 13:26
Hey , @matheusfelipeog can you assign this issue to me. I can fix it.

**Comment by pawelborkar** [comment] 2021-10-03 14:24
> Hey , @matheusfelipeog can you assign this issue to me. I can fix it.

It's not a bug to fix @Ritika457 

This has been opened for the announcement purpose.

You can contribute to the project by adding an API or more to the project which it doesn't contains at present. And if you're going ahead to do so please make sure you read the [Contributing Guide ](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md)


Thanks

**Comment by cyberbuddy-manas** [comment] 2021-10-03 15:47
@pawelborkar Hey, do we need to open a new issue or directly submit our pr? Also will you guys be adding issues to fix bugs or add upgrades or do we need to create our new apis? Thank you in advance for helping me out!!

**Comment by elenajp** [comment] 2021-10-03 16:10
Sounds, great! I would love to contribute. Happy hacktoberfest everyone 🥳

**Comment by pawelborkar** [comment] 2021-10-03 20:13
>Hey, do we need to open a new issue or directly submit our pr? 

You you know any public API which hasn't been added to the project uptil now then go ahead and make a PR or if you found any bug/typo feel free to do the same but first open the issue if you found any bug

>Also will you guys be adding issues to fix bugs or add upgrades or do we need to create our new apis?

If we find any we'll adding them in the issues but we also encourage you to find them as well and you don't need to create an API just for the sake of adding it into the project, make sure it can used by other developers in their projects which can be personal projects as well

**Comment by pawelborkar** [comment] 2021-10-03 20:17
> Sounds, great! I would love to contribute. Happy hacktoberfest everyone 🥳

Thanks, Please go ahead. Happy Hacktoberfest to you too ☺️

**Comment by elenajp** [comment] 2021-10-03 21:11
> > Sounds, great! I would love to contribute. Happy hacktoberfest everyone 🥳
> 
> Thanks, Please go ahead. Happy Hacktoberfest to you too ☺️

Done! This is such a useful list of APIs, thanks 😊

**Comment by RenatoLopes771** [comment] 2021-10-04 13:12
Hello @matheusfelipeog I believe we should look if the repository is valid for this year's hacktoberfest though. I don't think so, since it's a list of data.

A good way to check is to access the event with your github and check if your PR's show "awaiting review" or "excluded project".

**Comment by elenajp** [comment] 2021-10-04 13:28
I see it says excluded project

**Comment by matheusfelipeog** [comment] 2021-10-04 14:02
> Hello @matheusfelipeog I believe we should look if the repository is valid for this year's hacktoberfest though. I don't think so, since it's a list of data.

@RenatoLopes771 Really? I've read the content on the hacktoberfest website and haven't found anything stating that data lists are not valid projects. Can you tell me any links that inform this?

Even so, it seems to me that you are right. 😕 I'll try talking to Hacktoberfest to see what can be done.

**Comment by matheusfelipeog** [comment] 2021-10-04 14:07
If other contributors are seeing your contributions to Public APIs as "excluded project" in their [profile on the Hacktoberfest website](https://hacktoberfest.digitalocean.com/profile), please let us know.

**Comment by RenatoLopes771** [comment] 2021-10-04 14:09
> 
> 
> > Hello @matheusfelipeog I believe we should look if the repository is valid for this year's hacktoberfest though. I don't think so, since it's a list of data.
> 
> @RenatoLopes771 Really? I've read the content on the hacktoberfest website and haven't found anything stating that data lists are not valid projects. Can you tell me any links that inform this?
> 
> Even so, it seems to me that you are right. 😕 I'll try talking to Hacktoberfest to see what can be done.

The event has not been very good at telling what is a invalid project. This one obviously isn't spam but it fits into the invalid criteria. I had to look up their discord to see what fits into the invalid criteria, and it seems mostly "DSA's, lists" and so on. From what I understand, I think they only want people contributing code to software code bases this year.

I'm gonna request that you remove the hacktoberfest label though, since the project is not part of the event.

**Comment by RenatoLopes771** [comment] 2021-10-04 14:16
Nevermind. This one project that was DSA got it's invalid state removed. You could try talking to a hacktoberfest official to see if they remove the invalid state.

**Comment by MattIPv4** [comment] 2021-10-04 20:02
👋 This repo is not, and never has been, marked as excluded.

**Comment by Nirzak** [comment] 2021-10-04 20:12
Already contributed ago. I am looking forward to contributing more and also I would like to review the PRs if you want.

**Comment by RenatoLopes771** [comment] 2021-10-04 20:12
> 
> 
> 👋 This repo is not, and never has been, marked as excluded.

I'm glad to hear that. Sorry for the troubles.

Having a little of trouble understanding the event rules.

**Comment by matheusfelipeog** [comment] 2021-10-04 20:21
> 👋 This repo is not, and never has been, marked as excluded.

a big THANKS for letting us know @MattIPv4 ❤️🎉

I found it strange, as some contributors are getting the "excluded project" tag on their contributions, such as @elenajp 

> [I see it says excluded project](https://github.com/public-apis/public-apis/issues/2107#issuecomment-933486988)

and also revisions and merges by maintainers are not being accounted for in the profile:

![image](https://user-images.githubusercontent.com/50463866/135918918-1733afbb-0294-41e5-b25b-7dad1858a31d.png)

This is normal @MattIPv4?

**Comment by MattIPv4** [comment] 2021-10-04 20:24
> I found it strange, as some contributors are getting the "excluded project" tag on their contributions, such as @elenajp

I wonder if they're referring to a PR from a different repo, not this one? A PR submitted here definitely shouldn't be showing as exclude.

> and also revisions and merges by maintainers are not being accounted for in the profile:

The profile on the site only shows contributions from the perspective of a participant, not maintainer actions. We'll be doing a one-time check to calculate those at the end of Hacktoberfest.

**Comment by Nirzak** [comment] 2021-10-04 20:25
> > 👋 This repo is not, and never has been, marked as excluded.
> 
> a big THANKS for letting us know @MattIPv4 ❤️🎉
> 
> I found it strange, as some contributors are getting the "excluded project" tag on their contributions, such as @elenajp
> 
> > [I see it says excluded project](https://github.com/public-apis/public-apis/issues/2107#issuecomment-933486988)
> 
> and also revisions and merges by maintainers are not being accounted for in the profile:
> 
> ![image](https://user-images.githubusercontent.com/50463866/135918918-1733afbb-0294-41e5-b25b-7dad1858a31d.png)
> 
> This is normal @MattIPv4?

Go more below. there you will see your active PRs and I think this repository has been allowed for hacktoberfest because there's nothing showing excluded status for this repository and also the Maintainer actions will not be shown on profile, and will be tallied up in a one-time check performed by the Hacktoberfest team after Hacktoberfest has ended.

**Comment by matheusfelipeog** [comment] 2021-10-04 20:41
> I wonder if they're referring to a PR from a different repo, not this one? A PR submitted here definitely shouldn't be showing as exclude.

That's a good question. @elena, are you sure the PRs marked as "excluded project" refer to your contribution to the Public APIs? Can you take a screenshot and show us, please?

> The profile on the site only shows contributions from the perspective of a participant, not maintainer actions. We'll be doing a one-time check to calculate those at the end of Hacktoberfest.

Oh right @MattIPv4 / @Nirzak. It hadn't been so clear to me reading the content on the hacktoberfest website. Thank you again. 😅

**Comment by elenajp** [comment] 2021-10-05 08:13
I checked again and is all good at my end. I swear it said it wasn't earlier. Anyway the project is included now for me which is great!

**Comment by shangkaul** [comment] 2021-10-05 09:04
I had created a PR - #2279  but since I am a first-time contributor, workflow is awaiting approval. Do let me know if I'm missing a step here.

**Comment by Nirzak** [comment] 2021-10-05 10:33
> I had created a PR - #2279 but since I am a first-time contributor, workflow is awaiting approval. Do let me know if I'm missing a step here.

Your PR is fine but as you are a first-time contributor, a maintainer with write access has to approve the workflow. So, You might have to wait a little bit.

**Comment by squio** [comment] 2021-10-05 15:11
Just added the official Dutch open API for Air quality - a rich environmental API providing many air quality related components and excellent documentation.

PR  see https://github.com/public-apis/public-apis/pull/2328

**Comment by shangkaul** [comment] 2021-10-05 16:14
> > I had created a PR - #2279 but since I am a first-time contributor, workflow is awaiting approval. Do let me know if I'm missing a step here.
> 
> Your PR is fine but as you are a first-time contributor, a maintainer with write access has to approve the workflow. So, You might have to wait a little bit.

Oh okay, thanks for checking it out!

**Comment by abc516** [comment] 2021-10-05 17:08
Hi @matheusfelipeog, I would like to contribute to this project too

**Comment by matheusfelipeog** [comment] 2021-10-10 16:37
> i wanted ro add href link to the sponsored company with hover effect. in front view of hacktober fest

@RUDRANSH-hub We are not the organizers of the hacktoberfest event, just participants. We also don't have access to your site's source code.

**Comment by CodeForFun-JayeshP** [comment] 2021-10-15 09:49
I have work on an API program it will an honor to work on your repository. 
thank you

**Comment by QRiddler** [comment] 2021-10-15 10:51
Hi! can someone help me in finding what is wrong in the pr I made? #2419

**Comment by jennifertieuu** [comment] 2021-10-19 02:42
Love this! I would like to contribute to this as well. I am new to open source and participating in my first Hacktoberfest.

**Comment by Nirzak** [comment] 2021-10-19 05:18
> Love this! I would like to contribute to this as well. I am new to open source and participating in my first Hacktoberfest.

Take your time to go through whole repository and also read the contribution guidelines. Find out if any such API is remaining that you know but missing in this repository. Then don't forget to check on the pull requests section if any other one has already created a pull requests about that API. If not then fork this repository, add your API with all the details and create the pull request. Best of luck!

**Comment by fer-correa** [comment] 2021-11-01 00:03
PR [2872](https://github.com/public-apis/public-apis/pull/2872)

**Comment by matheusfelipeog** [comment] 2021-11-01 23:35
Community, the hacktoberfest is over. New PRs will no longer be counted for participation in the event.

I would like to thank everyone who participated in improving and expanding this huge list of APIs during this month. More than 500 pull requests were opened and all have been reviewed:

![image](https://user-images.githubusercontent.com/50463866/139755777-17e15162-536c-4be0-aa4d-34b760389f5a.png)

I hope you find what you need for your projects here ;)

A big thank you to everyone. ❤️

**Comment by olekstomek** [comment] 2021-11-02 20:01
Incredible amount of PR that definitely improves the API collection that will help many developers. Thanks too!

**Comment by Nirzak** [comment] 2021-11-02 20:06
It was a great experience to contribute to this project. Though hacktoberfest is ended, I will carry on my contribution whenever I get free time.

**Comment by pawelborkar** [comment] 2021-11-21 13:30
Thank you so much everybody for all the contribution and a big thanks to @matheusfelipeog for reviewing and merging the PRs. As the fest is over, I think we should close this issue/announcement [Ref.](https://github.com/public-apis/public-apis/issues/2107#issuecomment-956894412)

Once again thank you so much all of you 😊 And wish you all the very best for your further contributions to the open source community and your careers as well.✨ ❤️

**Closed by pawelborkar** 2021-11-21 13:30 UTC
Labels: hacktoberfest, good first issue
