### ISSUE TITLE
The links returning 404 should be removed.

### ISSUE THREAD

**Issue by marekdano** [public-apis/public-apis#1590] opened 2021-03-19 17:38 UTC
Here is a list of links that return 404

...

Please feel free to add more broken links when you find them.

**Comment by marekdano** [comment] 2021-03-19 17:38
Should we remove the broken link?

**Comment by matheusfelipeog** [comment] 2021-03-19 18:05
> Should we remove the broken links?

I believe so. I see no reason to keep them if they are broken. 🤔

**Comment by yannbertrand** [comment] 2021-03-22 19:50
Let's remove them 🙂

**Comment by PawelBorkar** [comment] 2021-03-24 22:44
Ofcourse.

**Comment by PawelBorkar** [comment] 2021-04-02 05:10
There's a PR regarding the link http://developer.linkedin.com/docs/rest-api . I had reviewed it and ask for the feedback of the author.

**Comment by Anmoldeep1509** [comment] 2021-04-02 14:59
Is the issue closed, if not, may I verify and remove the bad links?

**Comment by marekdano** [comment] 2021-04-02 15:09
The issue is still open.

**Comment by PawelBorkar** [comment] 2021-04-02 15:26
> Is the issue closed, if not, may I verify and remove the bad links?

Yeah! you can go ahead.

**Comment by Anmoldeep1509** [comment] 2021-04-03 19:25
API | STATUS | API STATUS
-- | -- | --
https://apility.io/apidocs/ | Already Removed | Down ❎
http://developer.linkedin.com/docs/rest-api | Already Removed | Down ❎
https://sentim-api.herokuapp.com/ | Already Removed | Up ✅
https://quarantine.country/coronavirus/api/ | Already Removed | Down ❎

**Comment by FrankR-7** [comment] 2021-04-12 02:30
I see the issue is still open. What if we made a script that periodically checks the links and alerts when any link is broken so we can manually remove it? (Or let it automatically remove the links)

**Comment by marekdano** [comment] 2021-04-12 14:16
@Anmoldeep1509 `https://quarantine.country/coronavirus/api/` is UP again.

**Comment by Anmoldeep1509** [comment] 2021-04-12 15:40
> https://quarantine.country/coronavirus/api/

yes, thanks, checked just now, it is working, updating the table, 

btw, do we have any md code to add beside the API - to show if it is up right or not?

Like I know a few repos where the md code checks if the website is up or not, similar will be needed for this case.

**Comment by Anmoldeep1509** [comment] 2021-04-12 15:41
> @Anmoldeep1509 `https://quarantine.country/coronavirus/api/` is UP again.

yes, thanks, checked just now, it is working, updating the table,

btw, do we have any md code to add beside the API - to show if it is up right or not?

Like I know a few repos where the md code checks if the website is up or not, similar will be needed for this case.

**Comment by marekdano** [comment] 2021-04-13 09:07
@yannbertrand do we have "MD code checks"?

**Comment by yannbertrand** [comment] 2021-04-13 19:45
What do you mean by MD code?

Btw I'd say it's a good API design practice to expose a `GET /status` endpoint

**Comment by Anmoldeep1509** [comment] 2021-04-14 17:56
> What do you mean by MD code?
> 
> Btw I'd say it's a good API design practice to expose a `GET /status` endpoint

wisdom at it's best <3

**Comment by Anmoldeep1509** [comment] 2021-04-14 18:36
Did the changes, please review PR #1641

**Comment by Anmoldeep1509** [comment] 2021-04-16 10:59
Pushed Changes - Please check PR #1650

**Comment by vmbansal2001** [comment] 2021-04-17 08:59
is this issue still open?

**Comment by PawelBorkar** [comment] 2021-04-18 12:59
> 
> 
> is this issue still open?

Yup please check if you can find one. Although the links mention [here](https://github.com/public-apis/public-apis/issues/1590#issue-836225522) has been fixed.

**Comment by ananya2023** [comment] 2021-05-03 04:06
I removed a broken link .Now where should I place the new code

**Comment by PawelBorkar** [comment] 2021-05-03 07:30
@ananya2023 
Please make a PR regarding the same.
We'll review it and if everything looks good, we'll either merge it into the master or give you a feedback.

**Comment by marekdano** [comment] 2021-05-03 10:56
@ananya2023 
[This guide](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md) can help you for creating a new PR.

**Comment by abitrolly** [comment] 2021-05-15 08:56
I am thinking about availability checker that will at least archive the reason for removal after few months (with an optional outreach and investigation if anyone is interested).

**Comment by pawelbr** [comment] 2021-05-15 15:10
@abitrolly 
Yeah. Sounds good.

**Comment by pawelbr** [comment] 2021-05-23 07:55
This link is broken
https://blog.mugenmonkey.com/2017/09/10/ds3-api.html

This URL is showing privacy notice
https://developer.walmartlabs.com/docs

**Comment by marekdano** [comment] 2021-05-25 17:53
This link is broken too
https://taylor.rest

**Comment by saisumanthkumar** [comment] 2021-05-27 04:04
If a link no longer allows new clients ,can we send a PR to remove that link ??

**Comment by saisumanthkumar** [comment] 2021-05-27 04:09
If a link no longer accepting new clients ,can we send a PR by removing that link ??

**Comment by pawelborkar** [comment] 2021-05-27 07:22
Sure

**Comment by saisumanthkumar** [comment] 2021-05-27 10:58
This URL no longer accepting new clients
https://www.behance.net/dev

**Comment by FarazzShaikh** [comment] 2021-06-23 04:10
Why not automate this with a bash script and a scheduled GitHub action?

**Comment by pawelborkar** [comment] 2021-06-23 07:00
> Why not automate this with a bash script and a scheduled GitHub action?
> 
> Edit: I suppose we'd need the base URL for all APIs listed here.

Ref. #1738

**Comment by hiraman33** [comment] 2021-08-15 14:40
hi

**Comment by hiraman33** [comment] 2021-08-15 14:42
how  to how to submit code on repository on github?

**Comment by pawelborkar** [comment] 2021-08-15 16:43
> hi

Hi @hiraman33 ,

Video:- https://youtu.be/wrb7Gge9yoE

Article:- https://tinyurl.com/push2github

**Comment by abitrolly** [comment] 2021-08-16 18:08
https://github.com/lycheeverse/lychee-action is capable of creating new issues when the check fails.

**Comment by matheusfelipeog** [comment] 2021-08-17 05:16
> https://github.com/lycheeverse/lychee-action is capable of creating new issues when the check fails.

Interesting @abitrolly 

We'll see and test it later to see if it's needed here. Thanks for letting us know. ;)

**Comment by matheusfelipeog** [comment] 2021-08-19 07:32
All links that return 404 have been removed. Thanks guys. 👏👏

Closing this issue.

**Closed** 2021-08-19 07:32 UTC
Labels: good first issue
